import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Verify from './components/verify'
import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  login,
  dashboard
}: Readonly<{
  children: React.ReactNode
  login: React.ReactNode
  dashboard: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Suspense fallback={<div>Loading ...</div>}>
          <Verify login={login} dashboard={dashboard}></Verify>
        </Suspense>
      </body>
    </html>
  )
}
