import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  analytics
}: Readonly<{
  children: React.ReactNode
  analytics: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col`}>
        {children}
        <nav className="flex items-center justify-center gap-6 py-4">
          <Link href="/page-views" className="hover:text-green-600">
            Page Views
          </Link>
          <Link href="/visitors" className="hover:text-green-600">
            Visitors
          </Link>
        </nav>
        {analytics}
      </body>
    </html>
  )
}
